"""adiciona origem em saidas_estoque

Revision ID: 601c544d3cbc
Revises: d16b57f58035
Create Date: 2026-07-13 22:02:28.605369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "601c544d3cbc"
down_revision: Union[str, Sequence[str], None] = "d16b57f58035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "saidas_estoque",
        sa.Column(
            "origem",
            sa.String(length=30),
            nullable=False,
            server_default="VENDA",
        ),
    )

    op.drop_column("saidas_estoque", "destino")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saidas_estoque",
        sa.Column(
            "destino", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("saidas_estoque", "origem")
    # ### end Alembic commands ###
