"""adiciona campos entrada estoque

Revision ID: 6c59bcfe3c42
Revises: 5729f2253571
Create Date: 2026-07-08 17:16:55.126089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c59bcfe3c42'
down_revision: Union[str, Sequence[str], None] = '5729f2253571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_estoque', sa.Column('origem', sa.String(length=30), nullable=False))
    op.add_column('entradas_estoque', sa.Column('numero_documento', sa.String(length=50), nullable=True))
    op.add_column('entradas_estoque', sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('entradas_estoque', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    op.alter_column('entradas_estoque', 'quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('entradas_estoque', 'custo_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('entradas_estoque', 'tipo_entrada')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_estoque', sa.Column('tipo_entrada', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('entradas_estoque', 'custo_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('entradas_estoque', 'quantidade',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('entradas_estoque', 'atualizado_em')
    op.drop_column('entradas_estoque', 'valor_total')
    op.drop_column('entradas_estoque', 'numero_documento')
    op.drop_column('entradas_estoque', 'origem')
    # ### end Alembic commands ###
