"""criar tabela produtos

Revision ID: 8801727298ed
Revises: 45754fede80b
Create Date: 2026-07-01 09:49:11.356018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8801727298ed'
down_revision: Union[str, Sequence[str], None] = '45754fede80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('preco_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
