"""alterar tabela fornecedores

Revision ID: 90dfad7d1ca2
Revises: a96e95ecc76e
Create Date: 2026-06-30 20:28:34.399954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dfad7d1ca2'
down_revision: Union[str, Sequence[str], None] = 'a96e95ecc76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedores', sa.Column('cpf_cnpj', sa.String(length=20), nullable=True))
    op.drop_column('fornecedores', 'cnpj')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedores', sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('fornecedores', 'cpf_cnpj')
    # ### end Alembic commands ###
