"""aumentar tamanho cpf_cnpj clientes

Revision ID: a96e95ecc76e
Revises: ac1e2c737a42
Create Date: 2026-06-30 17:26:44.330675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96e95ecc76e'
down_revision: Union[str, Sequence[str], None] = 'ac1e2c737a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)
    # ### end Alembic commands ###
