"""criar tabela movimentacoes_estoque

Revision ID: b1f9b9e2c3fd
Revises: 8801727298ed
Create Date: 2026-07-02 18:40:40.422974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f9b9e2c3fd'
down_revision: Union[str, Sequence[str], None] = '8801727298ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentacao'), nullable=False),
    sa.Column('origem', sa.Enum('COMPRA', 'VENDA', 'AJUSTE', 'DEVOLUCAO', 'PERDA', 'INVENTARIO', 'PRODUCAO', 'CONSUMO_INTERNO', 'OUTROS', name='origemmovimentacao'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_movimento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_estoque_id'), 'movimentacoes_estoque', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_estoque_id'), table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    # ### end Alembic commands ###
