"""adiciona entrada_id e saida_id em movimentacoes_estoque

Revision ID: d77961b54458
Revises: 40705924e43b
Create Date: 2026-07-17 17:14:10.740274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77961b54458'
down_revision: Union[str, Sequence[str], None] = '40705924e43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_estoque', sa.Column('entrada_id', sa.Integer(), nullable=True))
    op.add_column('movimentacoes_estoque', sa.Column('saida_id', sa.Integer(), nullable=True))
    op.add_column('movimentacoes_estoque', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimentacoes_estoque', 'saidas_estoque', ['saida_id'], ['id'])
    op.create_foreign_key(None, 'movimentacoes_estoque', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'movimentacoes_estoque', 'entradas_estoque', ['entrada_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimentacoes_estoque', type_='foreignkey')
    op.drop_constraint(None, 'movimentacoes_estoque', type_='foreignkey')
    op.drop_constraint(None, 'movimentacoes_estoque', type_='foreignkey')
    op.drop_column('movimentacoes_estoque', 'usuario_id')
    op.drop_column('movimentacoes_estoque', 'saida_id')
    op.drop_column('movimentacoes_estoque', 'entrada_id')
    # ### end Alembic commands ###
